[package]
name = "new"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
